# Generated by Django 3.0.2 on 2020-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='subcategory',
            field=models.TextField(default='None', verbose_name='Post Subkategoriyalari'),
        ),
    ]
