# Generated by Django 3.0.2 on 2020-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200123_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_id',
            field=models.IntegerField(verbose_name='Kommentin sahibi '),
        ),
    ]
